//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Web.WebForm.Account
{


    public partial class Manage
    {

        /// <summary>
        /// successMessage 控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從設計工具檔案移到程式碼後置 (Code-Behind) 檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder successMessage;

        /// <summary>
        /// setPassword 控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從設計工具檔案移到程式碼後置 (Code-Behind) 檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder setPassword;

        /// <summary>
        /// password 控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從設計工具檔案移到程式碼後置 (Code-Behind) 檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox password;



        /// <summary>
        /// confirmPassword 控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從設計工具檔案移到程式碼後置 (Code-Behind) 檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox confirmPassword;

        /// <summary>
        /// changePassword 控制項。
        /// </summary>
        /// <remarks>
        /// 自動產生的欄位。
        /// 若要修改，請將欄位宣告從設計工具檔案移到程式碼後置 (Code-Behind) 檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder changePassword;


    }
}
